/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutWatchlistRouteImport } from './routes/_layout/watchlist'
import { Route as LayoutUserProfileRouteImport } from './routes/_layout/userProfile'
import { Route as LayoutAboutRouteImport } from './routes/_layout/about'
import { Route as LayoutMoviesIndexRouteImport } from './routes/_layout/movies/index'
import { Route as LayoutMoviesMovieIdRouteImport } from './routes/_layout/movies/$movieId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWatchlistRoute = LayoutWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUserProfileRoute = LayoutUserProfileRouteImport.update({
  id: '/userProfile',
  path: '/userProfile',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAboutRoute = LayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMoviesIndexRoute = LayoutMoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMoviesMovieIdRoute = LayoutMoviesMovieIdRouteImport.update({
  id: '/movies/$movieId',
  path: '/movies/$movieId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/about': typeof LayoutAboutRoute
  '/userProfile': typeof LayoutUserProfileRoute
  '/watchlist': typeof LayoutWatchlistRoute
  '/': typeof LayoutIndexRoute
  '/movies/$movieId': typeof LayoutMoviesMovieIdRoute
  '/movies': typeof LayoutMoviesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/about': typeof LayoutAboutRoute
  '/userProfile': typeof LayoutUserProfileRoute
  '/watchlist': typeof LayoutWatchlistRoute
  '/': typeof LayoutIndexRoute
  '/movies/$movieId': typeof LayoutMoviesMovieIdRoute
  '/movies': typeof LayoutMoviesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/userProfile': typeof LayoutUserProfileRoute
  '/_layout/watchlist': typeof LayoutWatchlistRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/movies/$movieId': typeof LayoutMoviesMovieIdRoute
  '/_layout/movies/': typeof LayoutMoviesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/signup'
    | '/about'
    | '/userProfile'
    | '/watchlist'
    | '/'
    | '/movies/$movieId'
    | '/movies'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/about'
    | '/userProfile'
    | '/watchlist'
    | '/'
    | '/movies/$movieId'
    | '/movies'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/signup'
    | '/_layout/about'
    | '/_layout/userProfile'
    | '/_layout/watchlist'
    | '/_layout/'
    | '/_layout/movies/$movieId'
    | '/_layout/movies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/watchlist': {
      id: '/_layout/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof LayoutWatchlistRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/userProfile': {
      id: '/_layout/userProfile'
      path: '/userProfile'
      fullPath: '/userProfile'
      preLoaderRoute: typeof LayoutUserProfileRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/movies/': {
      id: '/_layout/movies/'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof LayoutMoviesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/movies/$movieId': {
      id: '/_layout/movies/$movieId'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof LayoutMoviesMovieIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutUserProfileRoute: typeof LayoutUserProfileRoute
  LayoutWatchlistRoute: typeof LayoutWatchlistRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutMoviesMovieIdRoute: typeof LayoutMoviesMovieIdRoute
  LayoutMoviesIndexRoute: typeof LayoutMoviesIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutUserProfileRoute: LayoutUserProfileRoute,
  LayoutWatchlistRoute: LayoutWatchlistRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutMoviesMovieIdRoute: LayoutMoviesMovieIdRoute,
  LayoutMoviesIndexRoute: LayoutMoviesIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
