/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserProfileFormRouteImport } from './routes/userProfileForm'
import { Route as SignUpRouteImport } from './routes/signUp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutWatchlistRouteImport } from './routes/_layout/watchlist'
import { Route as LayoutMoviesRouteImport } from './routes/_layout/movies'

const UserProfileFormRoute = UserProfileFormRouteImport.update({
  id: '/userProfileForm',
  path: '/userProfileForm',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/signUp',
  path: '/signUp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWatchlistRoute = LayoutWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMoviesRoute = LayoutMoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/signUp': typeof SignUpRoute
  '/userProfileForm': typeof UserProfileFormRoute
  '/movies': typeof LayoutMoviesRoute
  '/watchlist': typeof LayoutWatchlistRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/signUp': typeof SignUpRoute
  '/userProfileForm': typeof UserProfileFormRoute
  '/movies': typeof LayoutMoviesRoute
  '/watchlist': typeof LayoutWatchlistRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/signUp': typeof SignUpRoute
  '/userProfileForm': typeof UserProfileFormRoute
  '/_layout/movies': typeof LayoutMoviesRoute
  '/_layout/watchlist': typeof LayoutWatchlistRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/login'
    | '/signUp'
    | '/userProfileForm'
    | '/movies'
    | '/watchlist'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/login'
    | '/signUp'
    | '/userProfileForm'
    | '/movies'
    | '/watchlist'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/about'
    | '/login'
    | '/signUp'
    | '/userProfileForm'
    | '/_layout/movies'
    | '/_layout/watchlist'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  SignUpRoute: typeof SignUpRoute
  UserProfileFormRoute: typeof UserProfileFormRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/userProfileForm': {
      id: '/userProfileForm'
      path: '/userProfileForm'
      fullPath: '/userProfileForm'
      preLoaderRoute: typeof UserProfileFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signUp': {
      id: '/signUp'
      path: '/signUp'
      fullPath: '/signUp'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/watchlist': {
      id: '/_layout/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof LayoutWatchlistRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/movies': {
      id: '/_layout/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof LayoutMoviesRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutMoviesRoute: typeof LayoutMoviesRoute
  LayoutWatchlistRoute: typeof LayoutWatchlistRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutMoviesRoute: LayoutMoviesRoute,
  LayoutWatchlistRoute: LayoutWatchlistRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  SignUpRoute: SignUpRoute,
  UserProfileFormRoute: UserProfileFormRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
